### ISSUE TITLE
Preprocessor removes the numbers(preceded by space).

### ISSUE THREAD

**Issue by gitinpython** [s/preprocessor#15]
p.clean('I think we know what is 007')
#returns: I think we know what is
How can you clean data by removing only the hashtags and the urls and not the numbers?

**Comment by kLabille** [comment]
if you set the options manually and do not specify p.OPT.NUMBER 
p.set_options(p.OPT.URL, p.OPT.EMOJI, p.OPT.MENTION, p.OPT.HASHTAG)

it should work
