### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by alphagamer7** [s/preprocessor#16]
Error trace
Collecting tweet-preprocessor
  Downloading tweet-preprocessor-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-sgh4a7pq\tweet-preprocessor\setup.py", line 6, in <module>
        long_description = f.read()
      File "C:\Users\user\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 652: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-build-sgh4a7pq\tweet-preprocessor\

What is the issue ??

**Comment by machomachopadre** [comment]
Having the same issue

**Comment by s** [comment]
Thank you for the report and for the fix @rushatrai. This fix is included in `v0.6.0` branch. Cheers.
