### ISSUE TITLE
p.clean hangs on certain urls

### ISSUE THREAD

**Issue by carlomazzaferro** [s/preprocessor#19]
```
import preprocessor as p
def clean_text(sentence):
    p.set_options(p.OPT.URL)
    return p.clean(sentence)

a = 'canbe foundathttp://www.osp.gatech.edu/rates/(http://www.osp.gatech.edu/rates/).'
clean_text(a)
```

Running this snippet never returns, i.e. the code hangs. Any pointers at why this could be happening? I'm assuming this is a corner case -- http regex is repeated right next to the other and finditer never finds the end of the string. 

```
$ pip freeze | grep preprocessor
tweet-preprocessor==0.5.0
$ python -V
Python 3.6.1
```

**Comment by jalperin** [comment]
Also hanging on the following tweet text (when doing `p.parse`): 

```Nature：先日フランスで起きた臨床試験事故https://t.co/aHk5ok9CDg原因究明まだなので早急な印象がするけど、低用量投与を1回やった後で、(別のボランティアに）高用量の投与とかしてる試験方式にも問題があるだろうみたいなことを書いてる```

Adding a space after the URL (https://...CDg) makes it return successfully.

**Comment by uditarora** [comment]
Also hangs on the tweet - 

rt @comicmeteor: 単行本第２巻(https://t.co/klakewjz7y）が発売されたばかりの｢うちの姉ちゃんときたら！(https://t.co/qh2t1hivph）」が、｢pixivコミック(https://t.co/veefokclho)｣さんにて…

**Comment by s** [comment]
@carlomazzaferro the issue you reported will be fixed in `v.0.6.0`

**Comment by s** [comment]
@jalperin the issue you reported is fixed best as you suggested if you put a trailing space character. Because we cannot estimate the length of a url and thus it's hard to determine when it ends.

**Comment by s** [comment]
@MFajcik the tweet examples you give seems to be working in `v.0.6.0`.

**Comment by s** [comment]
Thanks for all the reports. String examples which are given in this issue are added to unit tests.
