### ISSUE TITLE
Mac Conda Install Error

### ISSUE THREAD

**Issue by Debugger28** [s/preprocessor#21]
Fetching package metadata ...........

PackageNotFoundError: Packages missing in current channels:
            
  - tweet-preprocessor

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by s** [comment]
Conda package will be published to support this.

**Comment by s** [comment]
You can install the conda package with following command:
`conda install -c saidozcan tweet-preprocessor`

**Comment by rtrad89** [comment]
I'm trying to install it too but I'm getting an error. Please see the output:

```
(base) PS C:\WINDOWS\system32> conda install -c saidozcan tweet-preprocessor
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - tweet-preprocessor

Current channels:

  - https://conda.anaconda.org/saidozcan/win-64
  - https://conda.anaconda.org/saidozcan/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
