### ISSUE TITLE
Windows installation issue Python 3.7

### ISSUE THREAD

**Issue by pdeitel** [s/preprocessor#25]
When installing in Windows 10 using the latest Anaconda with Python 3.7, I get the following error, which appears to be the same as what others are reporting on windows in prior versions of Python. iamRusty had fixed the issue with what appears to be a simple change at: https://github.com/iamRusty/preprocessor/blob/master/README.rst. Can you get this into the main package here? Thanks!

pip install tweet-preprocessor
Collecting tweet-preprocessor
  Using cached https://files.pythonhosted.org/packages/2a/f8/810ec35c31cca89bc4f1a02c14b042b9ec6c19dd21f7ef1876874ef069a6/tweet-preprocessor-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\PAULDE~1\AppData\Local\Temp\pip-install-w8wbkcrc\tweet-preprocessor\setup.py", line 6, in <module>
        long_description = f.read()
      File "c:\programdata\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 652: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\xxx\AppData\Local\Temp\pip-install-w8wbkcrc\tweet-preprocessor\

**Comment by Naklecha** [comment]
https://github.com/s/preprocessor/tree/master/preprocessor
Download and copy this folder and paste it into your site-packages folder in Python/Python35/Lib/site-packages (its equivalent to doing pip install)
Should work.

**Comment by s** [comment]
This will be fixed in `v0.6.0`. Thanks for reporting.
