### ISSUE TITLE
Not Installing

### ISSUE THREAD

**Issue by mtotri** [s/preprocessor#26]
I've been trying to install but it's not working. I tried the manual install as well using the setup.py. Getting error posted below.

Any help would be appreciated. 

![image](https://user-images.githubusercontent.com/47681127/52893310-02cfa300-3169-11e9-8b12-0a8ad0cddfae.png)

**Comment by PandaWhoCodes** [comment]
try this 
`python -m pip install git+https://github.com/s/preprocessor`

**Comment by RangoHU** [comment]
@PandaWhoCodes works for me. Many thanks.

**Comment by s** [comment]
Fix for this will be included in `v0.6.0`
