### ISSUE TITLE
Processing url bug

### ISSUE THREAD

**Issue by MingleiLI** [s/preprocessor#3]
If input sentence like this : 

> 'Loved sharing my favorite movie picks with @TribecaSL…my #shortlist is live now! https://t.co/JkgK0HI5vcccc'

The output will be:

> 'Loved sharing my favorite movie picks with \xe2\x80\xa6my #shortlist is live now! cccc'

It seems that there is length limitation for the URL?

**Comment by s** [comment]
Hello, 
I couldn't reproduce this. Which python and preprocessor version are you using? 
This screenshot from Python 2.7.11:
![screen shot 2016-05-12 at 15 10 59](https://cloud.githubusercontent.com/assets/1969638/15214097/cb91b40e-1853-11e6-8ce4-16d8c988fc93.png)

**Comment by s** [comment]
Closing the issue due to inactivity.
