### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by galacticfujiwara** [s/preprocessor#33]
pip install tweet-preprocessor ->    
ERROR: Command errored out with exit status 1:
     command: 'F:\Anaconda\pythonw.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user_name\\AppData\\Local\\Temp\\pip-install-0bxe_ypf\\tweet-preprocessor\\setup.py'"'"'; __file__='"'"'C:\\Users\\user_name\\AppData\\Local\\Temp\\pip-install-0bxe_ypf\\tweet-preprocessor\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user_name\AppData\Local\Temp\pip-pip-egg-info-76b_6umc'
         cwd: C:\Users\user_name\AppData\Local\Temp\pip-install-0bxe_ypf\tweet-preprocessor\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user_name\AppData\Local\Temp\pip-install-0bxe_ypf\tweet-preprocessor\setup.py", line 6, in <module>
        long_description = f.read()
      File "F:\Anaconda\lib\encodings\cp1254.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 652: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I am having this problem.
And this is the setup.y
with open('README.rst', encoding='utf-8') as f:
    long_description = f.read()
How can I install it

**Comment by s** [comment]
This will be fixed in `v0.6.0`. Thanks for reporting.
