### ISSUE TITLE
Got stuck

### ISSUE THREAD

**Issue by MingleiLI** [s/preprocessor#4]
When processing 

> t='Welcome to http://t.co/3YNnqG23S9(SAMSUNG,Kodak,bp,Coca-cola,Holcim,Nestle) 26.11.2013( http://t.co/9Xp7K7g3UW MAILAN(KISSME) SINCE 1969'

The program gets stuck....

**Comment by s** [comment]
I was able to reproduce this issue and it will be fixed in 0.6.0 version.
