### ISSUE TITLE
how can this package process a .txt file?

### ISSUE THREAD

**Issue by lululy** [s/preprocessor#5]
I save my tweets in .txt and then into an object called tweets. It has 33000 tweets. how can I use p.clean to clean them not just one by one?

Thank you!

**Comment by s** [comment]
Unfortunately currently there isn't any support for array of tweets. But to process all of them at single time, you can do something as follows:

```
tweets = ["@mention #hashtag bla bla", "That was nice though https://hashtag.com/", "#hashtag 😃  http://a.com/a"]
combined_tweets_string = ' __SEPERATOR__ '.join(tweets)
cleaned_combined_tweets = p.clean(combined_tweets_string)
```

**Comment by Byloor** [comment]
Hi, Following up this question.I have collected around 4000 tweets  in json format, how do I clean them up. Any progress? 
Thank you

**Comment by s** [comment]
Fixed in v.0.6.0
